### ISSUE TITLE
mcts_pure.py 中的 get_action() 函数 update_with_move(-1) 是否有误？

### ISSUE THREAD

**Issue by honeyshine75** [junxiaosong/AlphaZero_Gomoku#108]
请问这里的 update_with_move(-1) 是否应该改为 update_with_move(move)

**Comment by 1209805200** [comment]
您好，我对update_with_move(-1)也有一些疑惑，可以交流一下吗？reset_player和get_action里都是-1呐，不太理解其中的含义

**Comment by zwh6879a** [comment]
这个确实是有问题吧，不然每走一步都会重置决策树
