### ISSUE TITLE
如果想在15*15的棋盘上获得较好的结果，不知道pure_mcts和simulation的play out应大概设为多少呢？

### ISSUE THREAD

**Issue by 782832949** [junxiaosong/AlphaZero_Gomoku#13]

**Comment by 782832949** [comment]
还有其他参数还需要修改吗？

**Comment by junxiaosong** [comment]
理论上来说扩大棋盘时目前的play_out次数不用改，另外pure_mcts只是用来作为对照观察训练效果的，和训练过程无关。不过15 * 15的棋盘运算量要求太大了，如果是单机跑的话太慢了，基本是跑不出来的。

**Comment by 782832949** [comment]
嗯，打算用1080跑十几天。。。谢谢回复！

**Comment by junxiaosong** [comment]
@782832949 ，突然想到棋盘扩大之后dirichlet噪声的参数可能需要调整。根据AlphaZero论文里的描述， 这个参数一般按照反比于每一步的可行move数量设置，所以棋盘扩大之后这个参数可能需要减小。
具体是mcts_alphaZero.py中的[197行](https://github.com/junxiaosong/AlphaZero_Gomoku/blob/837ae459cc3f040f9505bbe000090178543d415c/mcts_alphaZero.py#L197)
 p=0.75 * probs + 0.25 * np.random.dirichlet(0.3 * np.ones(len(probs)))
其中的0.3可能减小一些（比如到0.1），会有帮助。不过我也没有实际跑大棋盘的经验，仅供参考。

**Comment by 782832949** [comment]
谢谢！还有，tensorflow保存的模型文件有.meta,.index,.data-00000-of-00001三个。载入的时候不能直接运行human_play，还要修改一下吧，好像要用tensorflow指定的载入方式？

**Comment by 782832949** [comment]
![1](https://user-images.githubusercontent.com/22772980/37404463-e36f91a6-27cc-11e8-9607-686871c024af.png)
![2](https://user-images.githubusercontent.com/22772980/37404464-e513471e-27cc-11e8-9009-f81536b1cb28.png)
如图，不知道为什么跑到这就卡在这不动了，cpu和磁盘占用都是0，是6*6*4的，用的tensorflow。

**Comment by BIGBALLON** [comment]
@782832949 刚好看到,顺手回答你的几个问题.

1. 15x15 的计算量太大, 1台机器不太可能train完.(保守估计十台以上的机器)
2. tensorflow的checkpoint有自己的载入方式,建议修改一些hunman vs.ai的code,如果有兴趣可以再pull request一下.
3. Ctrl+C就继续跑了,这个有可能是cmd lag住了.实际还在跑,知识终端没有输出(类似复制粘贴模式).也有可能是其他原因.

**Comment by junxiaosong** [comment]
@782832949 关于载入tensorflow保存的模型文件，我记得human_play.py里的代码是直接可以运行的，当然model_file = 后面不要写那三个文件名，而是写和train.py里保存时一样的名字，比如'best_policy.model'或者'current_policy.model'就可以了

**Comment by BIGBALLON** [comment]
@junxiaosong 提个小建议，建议不要使用pickle来save 和 load model的weight。可以直接用pytorch的内建API。速度快了接近100倍。 
(20层的resnet, pickle读取weight大概要20s，torch.load大概是0.2s)


大概是这样。
```
 def save_model(self,path):
        torch.save(self.policy_value_net.state_dict(),path)
        print("SAVE MODEL IN: ",path)

    def load_model(self,path):
        self.policy_value_net.load_state_dict(torch.load(path))
        print("LOAD MODEL FROM: ",path)
```

**Comment by BIGBALLON** [comment]
另外我有使用您的部分code来做我自己的五子棋。由于和硕士阶段的论文可能有关系。
所有不会open source。不过会reference您。

目前大概用的 10个residual block，filter number 128#
在self play 的地方和您有较大不同，然后就是training的时候也有较大不同。

目前9x9强度大概是能够和一般人下，先手一般会和。(和高手下会输，和yixin下必输)
有和Google play一些带9X9棋盘的app下，能够取胜。
先手应该是一定不会输。

BTW, a good toy demo for everyone!

**Comment by 782832949** [comment]
谢谢~

**Comment by Kelvin-Zhong** [comment]
@BIGBALLON  你的9x9 是训练了多久呢？

**Comment by BIGBALLON** [comment]
@Kelvin-Zhong Hello. 


首先是机器:

- CPU: 8 core i7-7700 CPU @ 3.60GHz
- GPU: GeForce GTX 1080TI x 1
- MEMORY: 32G (DDR4-2400 16G * 2)

最近有一个版本,
练了15天,累计训练时间300+小时.
强度的话可以打败一个中级水平的成年人.
细节有点多.我挑一些讲.
- 我用的10个block的residual net, filter数量是128.
- 我用了一个进程负责 self-play 和 training的部分, 另外4个进程只负责self-play的部分.
- 另外我用的是SGD 不是 Adam. 原因是Adam不会收敛地比SGD好(可以参考[Adam那么棒，为什么还对SGD念念不忘](https://zhuanlan.zhihu.com/p/32338983) 和 传统的classification的 state-of art 方法都是通过 SGD tune出来的.)
- 另外需要留意的地方是前N收的temperature的设定,在前N手应该是按概率下器,随后再跳到选择概率最大的下法落字
- 值得留意的是还应该注意 self-play生成的training data 和 optimizer 训练时候的对应比例.换句话说就是一笔资料大概会训练到几次.(从alpha zero来分析就可以看出, 他们用的大概5000TPU, 64GPU, TPU主要是产生棋谱, 训练用的的资源要少得多,应该traiing远比self-play要快,具体可以参考[这个](https://github.com/mokemokechicken/reversi-alpha-zero/issues/38)讨论)
- 以及一个需要根据legal move来调整的dirichlet,和exploration有很大的关系,也是要考虑.

另外还可以参考一个练得不错的 [黑白棋](https://github.com/mokemokechicken/reversi-alpha-zero/blob/master/challenge_history.md) ,或者参考这个 [here](https://github.com/gooooloo/reversi-alpha-zero/blob/master/records.md)
前前后后也尝试训练了4个月的时间.
值得一提的是,黑白棋的legal move实际上比五子棋少很多.而且棋盘大小只有8X8.从这两点可以看出,训练黑白棋其实不会比训练五子棋难(另外8x8的棋盘还较容易用bitborad来实现,加快程序的效率,在MCTS上,他们也有实现virtual loss来进行多线程并行来加速.)

顺便说一下,要想达到真的打败很顶尖的AI或者棋手的强度.在上面这些参数都调对的情况下,可能需要准备尽可能多的机器,并且优化代码. 
Alphago zero用了3天打败人类.这个真的是三天吗?普通实验室的设备,可以换算成三年,个人PC电脑的话,怕是要300年.

大概只能讲这么多了..

Good luck!

**Comment by initial-h** [comment]
@BIGBALLON你好
请问怎么把AI连到一个平台上去比较呢，我下了piskvork但是只有python2的模板。python3打包成exe有很多报错，你是连的哪一个呢？

**Comment by gmftbyGMFTBY** [comment]
@BIGBALLON 比较关心 9 * 9 的硬件配置和训练的时间大小，谢谢了
