### ISSUE TITLE
如果是可以走棋的游戏 action网络应该怎样设计？

### ISSUE THREAD

**Issue by fupip** [junxiaosong/AlphaZero_Gomoku#21]
围棋和五子棋都是放下后不可移动，所以action和evaluation共用了一部分网络
如果是象棋跳棋类型，应该怎么设计这个action网络部分呢？
能否提供一点思路？

**Comment by BIGBALLON** [comment]
象棋的话参考第三篇paper 
"Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm." (2017). [arXiv:1712.01815]

将棋 和 象棋 基本上都是暴力展开(稍微有用一点trick减少一点dim)
paper后面有很详细的说明用了那些

**Comment by fupip** [comment]
好的，谢谢。我 去看一下。
