### ISSUE TITLE
gif是用什么画出来的呢

### ISSUE THREAD

**Issue by initial-h** [junxiaosong/AlphaZero_Gomoku#23]
RT

**Comment by junxiaosong** [comment]
这是网上找的一个gif录屏小软件录的，具体名字记不清了，搜一下相关的应该不少

**Comment by initial-h** [comment]
我在windows终端运行的时候，棋盘是print出来的，一行一行向上，视频没有这么平滑。

**Comment by junxiaosong** [comment]
我当时应该是在一个IDE里运行的，倒是没有上下跳动的现象，每次print都在相同的位置的
