### ISSUE TITLE
请问实际对弈的时候，把np.ramdom.choice改成直接选最大概率会不会更好

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [junxiaosong/AlphaZero_Gomoku#58]
如题

**Comment by junxiaosong** [comment]
现在实际对弈时，参数temp使用的是默认值10^-3，在这个参数下访问次数最多的分支基本对应概率1，其他分支概率几乎全0，所以用random choice也是会选择访问次数最多的那个分支。代码的注释中有提到这一点。

**Comment by gmftbyGMFTBY** [comment]
明白了，非常感谢
