### ISSUE TITLE
tensorflow 版本的网络action_fc的激活函数是log_softmax？

### ISSUE THREAD

**Issue by initial-h** [junxiaosong/AlphaZero_Gomoku#67]
self.action_fc = tf.layers.dense(inputs=self.action_conv_flat,
                                         units=board_height * board_width,
                                         activation=tf.nn.log_softmax)
应该是softmax吧？
是为了后面好算吗？

**Comment by junxiaosong** [comment]
这个关系不大的，只要后面用的时候知道输出的是log_act_probs，比如后面计算loss的时候需要log_act_probs就直接用，如果要计算act_probs的时候求个exp()即可。
