### ISSUE TITLE
如何把现在的Net网络改成Resnet网络

### ISSUE THREAD

**Issue by liunian321** [junxiaosong/AlphaZero_Gomoku#78]
我在15x15的棋盘上已经跑了4500盘，这个Ai下棋还是非常非常差劲。（四个角轮流下，也不会堵我的子）
噪声，温度，学习率都尝试改过了，没什么作用。通过翻转扩充self-play数据，我觉得这是不可行的。
想问如何现在net改成resnet。。查了下相关资料，一头雾水。。
还有如果把7x7或8x8之类比较小的板训练的Ai应用到更大的15x15之类的，会不会训练快很多呢？（但是目前好像大小不一致是不能这样用的。。）

**Comment by liunian321** [comment]
> 主要还是下棋数量太少了，我用resnet网络训练了一个11x11的AI，训练了十万盘左右，得到了一个比较强的AI.15×15的棋盘我估计要百万级别的训练量。
贫穷限制了我的想象力。。
另外能问问你怎么改的ResNet吗？。。

**Comment by initial-h** [comment]
就直接写一个就行，你点我的github进去那个五子棋的repo，代码里有。

**Comment by liunian321** [comment]
> 就直接写一个就行，你点我的github上进去那个五子棋的回购，代码里有。

非常感谢！
